#!/bin/bash

# note double escape for PS1:
# e.g. C_RESET='\[\e[0m\]'

C_RESET='\e[0m'
C_BLINK='\e[5m'
C_BOLD='\e[1m'
C_BLACK='\e[30m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'
C_BLUE='\e[34m'
C_MAGENTA='\e[35m'
C_CYAN='\e[36m'
C_LIGHT_GRAY='\e[37m'
C_DEFAULT='\e[39m'
C_DARK_GRAY='\e[90m'
C_LIGHT_RED='\e[91m'
C_LIGHT_GREEN='\e[92m'
C_LIGHT_YELLOW='\e[93m'
C_LIGHT_BLUE='\e[94m'
C_LIGHT_MAGENTA='\e[95m'
C_LIGHT_CYAN='\e[96m'
C_WHITE='\e[97m'

# palette
PALETTE=("C_RED" "C_GREEN" "C_YELLOW" "C_MAGENTA" "C_CYAN" "C_WHITE")

X=$(($RANDOM % ${#PALETTE[@]}))
Y=$(($RANDOM % ${#PALETTE[@]}))

PS1_PRIMARY_COLOR=${PALETTE[$X]}
PS1_SECONDARY_COLOR=${PALETTE[$Y]}

C_PRIMARY=${!PS1_PRIMARY_COLOR}
C_SECONDARY=${!PS1_SECONDARY_COLOR}

echo -e "${C_PRIMARY}${PS1_PRIMARY_COLOR}${C_RESET}:${C_SECONDARY}${PS1_SECONDARY_COLOR}${C_RESET}"
